# Application
spring.application.name=trustrail-api

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

serve.port=8080



# JPA / Hibernate
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Jackson Configuration
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Africa/Lagos

# JWT Configuration
jwt.secret=H61FrpbiJ7xp7WkMjr7Dm43JGCF7PXm2t5ZxCzCKnKQ=
jwt.expiration=86400000

# PayWithAccount API Configuration
pwa.base-url=https://api.dev.onepipe.io
pwa.api-key=${PWA_API_KEY:1Y94X91d9gDRaTQ9IakS_26b848f8c6ab42c9910a2708dfb05c99}
pwa.secret-key=${PWA_SECRET_KEY:dRalHAbheKczKXbY}
pwa.biller-code=${PWA_BILLER_CODE:000753}

# Server Configuration
server.port=8080
server.servlet.context-path=/api

# Logging
logging.level.trustrail.api=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha