package trustrail.api.entity.enums;

public enum AuditEventType {
    TRUST_SCORE_CHANGED,
    ELIGIBILITY_CHECKED,
    MANDATE_CREATED,
    MANDATE_ACTIVATED,
    MANDATE_REVOKED,
    PAYMENT_SCHEDULED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    PAYMENT_SKIPPED,
    CUSTOMER_RESTRICTED,
    CUSTOMER_UNRESTRICTED,
    POLICY_OVERRIDE
}
